//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashandCarry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SaleRecovery
    {
        public int SRecoveryID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> RInvoice { get; set; }
        public Nullable<decimal> ReturnCash { get; set; }
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        public Nullable<int> RecoveryBatchNo { get; set; }
    }
}
