//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashandCarry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_employee
    {
        public int EmployeeID { get; set; }
        public string Name { get; set; }
        public string Fname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Qualifiction { get; set; }
        public string DOB { get; set; }
        public string Cnic { get; set; }
        public string Contact { get; set; }
        public string Designation { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Address { get; set; }
    }
}
