//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashandCarry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SubZone
    {
        public int SubRouteId { get; set; }
        public string SubRouteName { get; set; }
        public Nullable<int> ZoneID { get; set; }
    }
}
