//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashandCarry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SaleMAster
    {
        public int Invoice_ { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> DuePayment { get; set; }
        public string OrderBy { get; set; }
        public Nullable<decimal> ProfitLoss { get; set; }
    }
}
