//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashandCarry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PurchaseRemain
    {
        public int PRemainID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> PReturnID { get; set; }
        public Nullable<decimal> ReturnCash { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
