//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashandCarry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductPrice
    {
        public int ProductPriceId { get; set; }
        public string ProductName { get; set; }
        public Nullable<decimal> BuyerPrice { get; set; }
        public Nullable<decimal> SellerPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
