//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashandCarry.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PurLedger
    {
        public int PTId { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Contact { get; set; }
        public Nullable<int> PInvoice { get; set; }
        public Nullable<int> PRemainID { get; set; }
        public Nullable<int> PReturnID { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Description { get; set; }
    }
}
